# ConfigMap for API Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: project-gp-2
data:
  PORT: "5000"
  NODE_ENV: "production"
  CORS_ORIGIN: "https://tissea-grp2.apps.openshift.kakor.ovh"
  JWT_SECRET: "your-secret-key-change-me-in-production"