apiVersion: apps/v1
kind: Deployment
metadata:
  name: tissea-back
  namespace: project-gp-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tissea-back
  template:
    metadata:
      labels:
        app: tissea-back
    spec:
      containers:
        - name: tissea-back
          image: harbor.kakor.ovh/ipi/ipi-grp-2-back:latest
          ports:
            - containerPort: 5000
          securityContext:
            allowPrivilegeEscalation: true
